FROM condaforge/miniforge3:latest AS build

RUN mamba update -y -n base -c conda-forge -y mamba

RUN mkdir conda-channel
COPY conda-channel /conda-channel/

RUN mamba create -n gpf -y
RUN mamba install -y -n gpf \
    -c conda-forge \
    -c bioconda \
    -c file:///conda-channel \
    gpf_dae

