name: gpf-web-annotation
services:
  backend:
    build:
      dockerfile: Dockerfile.backend

  frontend:
    build:
      dockerfile: Dockerfile.frontend

  e2e:
    build:
      dockerfile: Dockerfile.e2e
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_healthy
