name: gpf-web-annotation
services:

  mail:
    image: mailhog/mailhog
    hostname: mail

  rabbitmq:
    image: rabbitmq
    hostname: rabbitmq

  backend:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "80:80"
    environment:
      DJANGO_SETTINGS_MODULE: gpf_web_annotation_project.settings
      WDAE_EMAIL_HOST: mail
      RABBITMQ_HOST: rabbitmq
      GRR_DEFINITION_FILE: /grr-definition.yaml
