FROM ubuntu:24.04 AS runtime

RUN DEBIAN_FRONTEND=noninteractive apt-get update --fix-missing
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y \
		supervisor curl less wget
RUN DEBIAN_FRONTEND=noninteractive apt-get clean
