FROM ubuntu:24.04 AS runtime

RUN DEBIAN_FRONTEND=noninteractive \
    apt-get update && apt-get install -y --no-install-recommends \
        apache2 \
        curl \
        less \
        wget \
		supervisor \
    && rm -rf /var/lib/apt/lists/*

