FROM gpfwa-gpf-dev:latest

ARG DOCKER_UID=1001
COPY scripts/grr-definition.yaml /
WORKDIR /app

COPY environment.yml .
COPY dev-environment.yml .
RUN mamba env update -y -n gpf --file ./environment.yml
RUN mamba env update -y -n gpf --file ./dev-environment.yml
