ARG COMPOSE_PROJECT_NAME=gpfwa
FROM ${COMPOSE_PROJECT_NAME}-gpf-image:latest

COPY scripts/grr-definition.yaml /
WORKDIR /app

COPY environment.yml .
COPY dev-environment.yml .
RUN mamba env update -y -n gpf --file ./environment.yml
RUN mamba env update -y -n gpf --file ./dev-environment.yml
