# Generated by Django 5.2.5 on 2025-10-10 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_annotation', '0002_resetpasswordcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='config_path',
            field=models.FilePathField(path='/tmp/gpf-web-annotation-tests-data-1760090204/annotation-configs'),
        ),
        migrations.AlterField(
            model_name='job',
            name='input_path',
            field=models.FilePathField(path='/tmp/gpf-web-annotation-tests-data-1760090204/job-inputs'),
        ),
        migrations.AlterField(
            model_name='job',
            name='result_path',
            field=models.FilePathField(path='/tmp/gpf-web-annotation-tests-data-1760090204/job-results'),
        ),
        migrations.CreateModel(
            name='AccountConfirmationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account_confirmation_codes',
            },
        ),
    ]
