# Generated by Django 5.2.5 on 2025-10-16 08:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_annotation', '0003_alter_job_config_path_alter_job_input_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='config_path',
            field=models.FilePathField(path='/tmp/gpf-web-annotation-tests-data-1760602690/annotation-configs'),
        ),
        migrations.AlterField(
            model_name='job',
            name='input_path',
            field=models.FilePathField(path='/tmp/gpf-web-annotation-tests-data-1760602690/job-inputs'),
        ),
        migrations.AlterField(
            model_name='job',
            name='result_path',
            field=models.FilePathField(path='/tmp/gpf-web-annotation-tests-data-1760602690/job-results'),
        ),
    ]
