# Generated by Django 5.2.5 on 2025-10-13 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_annotation", "0003_alter_job_config_path_alter_job_input_path_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="config_path",
            field=models.FilePathField(path="data/annotation-configs"),
        ),
        migrations.AlterField(
            model_name="job",
            name="input_path",
            field=models.FilePathField(path="data/job-inputs"),
        ),
        migrations.AlterField(
            model_name="job",
            name="result_path",
            field=models.FilePathField(path="data/job-results"),
        ),
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "Specifying"),
                    (2, "Waiting"),
                    (3, "In Progress"),
                    (4, "Success"),
                    (5, "Failed"),
                ],
                default=2,
            ),
        ),
        migrations.CreateModel(
            name="JobDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chr_col", models.CharField(max_length=64)),
                ("pos_col", models.CharField(max_length=64)),
                ("ref_col", models.CharField(max_length=64)),
                ("alt_col", models.CharField(max_length=64)),
                ("separator", models.CharField(max_length=1)),
                ("columns", models.TextField()),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="web_annotation.job",
                    ),
                ),
            ],
        ),
    ]
