# Generated by Django 5.2.5 on 2025-10-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_annotation', '0004_job_created_at_job_is_active_alter_job_config_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='config_path',
            field=models.FilePathField(path='/tmp/gpf-web-annotation-tests-data-1760602708/annotation-configs'),
        ),
        migrations.AlterField(
            model_name='job',
            name='input_path',
            field=models.FilePathField(path='/tmp/gpf-web-annotation-tests-data-1760602708/job-inputs'),
        ),
        migrations.AlterField(
            model_name='job',
            name='result_path',
            field=models.FilePathField(path='/tmp/gpf-web-annotation-tests-data-1760602708/job-results'),
        ),
    ]
