# Generated by Django 5.2.5 on 2025-10-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_annotation", "0004_alter_job_config_path_alter_job_input_path_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="jobdetails",
            constraint=models.UniqueConstraint(
                fields=("job",), name="unique_job_details"
            ),
        ),
    ]
