# Generated by Django 5.2.5 on 2025-10-16 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web_annotation", "0005_jobdetails_unique_job_details"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jobdetails",
            old_name="alt_col",
            new_name="col_alt",
        ),
        migrations.RenameField(
            model_name="jobdetails",
            old_name="chr_col",
            new_name="col_chr",
        ),
        migrations.RenameField(
            model_name="jobdetails",
            old_name="pos_col",
            new_name="col_pos",
        ),
        migrations.RenameField(
            model_name="jobdetails",
            old_name="ref_col",
            new_name="col_ref",
        ),
    ]
