# Generated by Django 5.2.5 on 2025-10-17 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web_annotation", "0005_alter_job_config_path_alter_job_input_path_and_more"),
        ("web_annotation", "0006_rename_alt_col_jobdetails_col_alt_and_more"),
    ]

    operations = []
