# Generated by Django 5.2.5 on 2025-10-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_annotation', '0007_merge_20251017_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='reference_genome',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='job',
            name='config_path',
            field=models.FilePathField(path='data/annotation-configs'),
        ),
        migrations.AlterField(
            model_name='job',
            name='input_path',
            field=models.FilePathField(path='data/job-inputs'),
        ),
        migrations.AlterField(
            model_name='job',
            name='result_path',
            field=models.FilePathField(path='data/job-results'),
        ),
    ]
