# Generated by Django 5.2.5 on 2025-10-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_annotation', '0007_merge_20251017_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='col_cnv_type',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='jobdetails',
            name='col_location',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='jobdetails',
            name='col_pos_beg',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='jobdetails',
            name='col_pos_end',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='jobdetails',
            name='col_variant',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='jobdetails',
            name='col_vcf_like',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='job',
            name='config_path',
            field=models.FilePathField(path='data/annotation-configs'),
        ),
        migrations.AlterField(
            model_name='job',
            name='input_path',
            field=models.FilePathField(path='data/job-inputs'),
        ),
        migrations.AlterField(
            model_name='job',
            name='result_path',
            field=models.FilePathField(path='data/job-results'),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='col_alt',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='col_chr',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='col_pos',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='col_ref',
            field=models.CharField(default='', max_length=64),
        ),
    ]
