# Generated by Django 5.2.5 on 2025-10-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_annotation', '0008_job_reference_genome_alter_job_config_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='col_cnv_type',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='jobdetails',
            name='col_location',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='jobdetails',
            name='col_pos_beg',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='jobdetails',
            name='col_pos_end',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='jobdetails',
            name='col_variant',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='jobdetails',
            name='col_vcf_like',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='col_alt',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='col_chr',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='col_pos',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='col_ref',
            field=models.CharField(default='', max_length=64),
        ),
    ]
