# Generated by Django 5.2.6 on 2025-10-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_annotation', '0009_jobdetails_col_cnv_type_jobdetails_col_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='reference_genome',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='col_alt',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='col_chr',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='col_cnv_type',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='col_location',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='col_pos',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='col_pos_beg',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='col_pos_end',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='col_ref',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='col_variant',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='col_vcf_like',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
