# Generated by Django 5.2.5 on 2025-10-27 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "web_annotation",
            "0010_alter_job_reference_genome_alter_jobdetails_col_alt_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="created_at",
        ),
    ]
