# Generated by Django 5.2.5 on 2025-10-27 13:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_annotation", "0011_remove_job_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
