# Generated by Django 5.2.5 on 2025-10-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_annotation", "0012_alter_job_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="duration",
            field=models.FloatField(default=None, null=True),
        ),
    ]
