# Generated by Django 5.2.5 on 2025-10-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_annotation', '0013_job_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='separator',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
