# Generated by Django 5.2.5 on 2025-10-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_annotation', '0014_alter_jobdetails_separator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.IntegerField(choices=[(1, 'Waiting'), (2, 'In Progress'), (3, 'Success'), (4, 'Failed')], default=1),
        ),
    ]
