# Generated by Django 5.2.5 on 2025-10-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_annotation', '0015_alter_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='command_line',
            field=models.TextField(default=''),
        ),
    ]
