# Generated by Django 5.2.5 on 2025-11-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_annotation', '0016_job_command_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='annotation_type',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='job',
            name='config_path',
            field=models.FilePathField(path='/home/ivostefanov/gpf-web-annotation/backend/data/annotation-configs'),
        ),
        migrations.AlterField(
            model_name='job',
            name='input_path',
            field=models.FilePathField(path='/home/ivostefanov/gpf-web-annotation/backend/data/job-inputs'),
        ),
        migrations.AlterField(
            model_name='job',
            name='result_path',
            field=models.FilePathField(path='/home/ivostefanov/gpf-web-annotation/backend/data/job-results'),
        ),
    ]
