# Generated by Django 5.2.5 on 2025-11-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_annotation', '0018_pipeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='name',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='job',
            name='config_path',
            field=models.FilePathField(path='/tmp/gpf-web-annotation-tests-data-1763025225/annotation-configs'),
        ),
        migrations.AlterField(
            model_name='job',
            name='input_path',
            field=models.FilePathField(path='/tmp/gpf-web-annotation-tests-data-1763025225/job-inputs'),
        ),
        migrations.AlterField(
            model_name='job',
            name='result_path',
            field=models.FilePathField(path='/tmp/gpf-web-annotation-tests-data-1763025225/job-results'),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='config_path',
            field=models.FilePathField(path='/tmp/gpf-web-annotation-tests-data-1763025225/annotation-configs'),
        ),
    ]
