# Generated by Django 5.2.5 on 2025-11-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_annotation', '0019_job_name_alter_job_config_path_alter_job_input_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='config_path',
            field=models.FilePathField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='input_path',
            field=models.FilePathField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='result_path',
            field=models.FilePathField(),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='config_path',
            field=models.FilePathField(),
        ),
    ]
