# Generated by Django 5.2.5 on 2025-11-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_annotation', '0020_alter_job_config_path_alter_job_input_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
