# Generated by Django 5.2.5 on 2025-11-17 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_annotation', '0021_pipeline_is_anonymous'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlleleQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allele', models.CharField(max_length=1024)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allele_query', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
