# Generated by Django 5.2.5 on 2025-11-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_annotation', '0022_allelequery'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='disk_size',
            field=models.IntegerField(default=0),
        ),
    ]
