# Generated by Django 5.2.5 on 2025-11-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_annotation", "0023_job_disk_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="error",
            field=models.TextField(default=""),
        ),
    ]
