# Generated by Django 5.2.5 on 2025-11-27 08:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_annotation', '0023_job_disk_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_path', models.FilePathField()),
                ('config_path', models.FilePathField()),
                ('result_path', models.FilePathField()),
                ('name', models.IntegerField(default=0)),
                ('reference_genome', models.CharField(default='', max_length=1024)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.IntegerField(choices=[(1, 'Waiting'), (2, 'In Progress'), (3, 'Success'), (4, 'Failed')], default=1)),
                ('duration', models.FloatField(default=None, null=True)),
                ('command_line', models.TextField(default='')),
                ('annotation_type', models.CharField(default='', max_length=1024)),
                ('disk_size', models.IntegerField(default=0)),
                ('owner', models.CharField(max_length=1024)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
