# Generated by Django 5.2.5 on 2025-12-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_annotation', '0024_anonymousjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymousjob',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
