# Generated by Django 5.2.5 on 2025-12-04 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_annotation', '0025_anonymousjob_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousJobDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col_chr', models.CharField(default='', max_length=1024)),
                ('col_pos', models.CharField(default='', max_length=1024)),
                ('col_ref', models.CharField(default='', max_length=1024)),
                ('col_alt', models.CharField(default='', max_length=1024)),
                ('col_pos_beg', models.CharField(default='', max_length=1024)),
                ('col_pos_end', models.CharField(default='', max_length=1024)),
                ('col_cnv_type', models.CharField(default='', max_length=1024)),
                ('col_vcf_like', models.CharField(default='', max_length=1024)),
                ('col_variant', models.CharField(default='', max_length=1024)),
                ('col_location', models.CharField(default='', max_length=1024)),
                ('separator', models.CharField(max_length=1, null=True)),
                ('columns', models.TextField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='web_annotation.anonymousjob')),
            ],
            options={
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('job',), name='unique_anonymous_job_details')],
            },
        ),
    ]
