# Generated by Django 5.2.5 on 2025-12-03 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web_annotation", "0024_job_error"),
        ("web_annotation", "0025_anonymousjob_is_active"),
    ]

    operations = []
