# Generated by Django 5.2.5 on 2025-12-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_annotation", "0026_merge_0024_job_error_0025_anonymousjob_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="anonymousjob",
            name="error",
            field=models.TextField(default=""),
        ),
    ]
