# Generated by Django 5.2.5 on 2025-12-04 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web_annotation", "0026_anonymousjobdetails"),
        ("web_annotation", "0027_anonymousjob_error"),
    ]

    operations = []
