# Generated by Django 5.2.5 on 2025-12-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_annotation', '0028_merge_20251204_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymousjob',
            name='ip',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='anonymousjob',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
