# Generated by Django 5.2.5 on 2025-12-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_annotation', '0029_anonymousjob_ip_alter_anonymousjob_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousPipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=1024)),
                ('config_path', models.FilePathField()),
                ('is_temporary', models.BooleanField(default=False)),
                ('owner', models.CharField(max_length=1024)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='pipeline',
            old_name='is_anonymous',
            new_name='is_temporary',
        ),
    ]
