# Generated by Django 5.2.5 on 2026-01-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_annotation', '0030_anonymouspipeline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='job_counter',
            field=models.IntegerField(default=0),
        ),
    ]
