# Generated by Django 5.2.5 on 2026-01-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_annotation', '0031_user_job_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymousjob',
            name='name',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(max_length=1024),
        ),
    ]
