# Generated by Django 5.2.5 on 2026-01-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_annotation', '0033_alter_anonymousjob_name_alter_job_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymousjob',
            name='name',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.BigIntegerField(default=0),
        ),
    ]
