# Generated by Django 5.2.5 on 2026-03-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_annotation", "0034_alter_anonymousjob_name_alter_job_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemporaryPipeline",
            fields=[
                ("name", models.CharField(default="", max_length=1024)),
                ("config_path", models.FilePathField()),
                (
                    "session_id",
                    models.CharField(
                        max_length=1024, primary_key=True, serialize=False
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="AnonymousPipeline",
        ),
        migrations.RemoveField(
            model_name="pipeline",
            name="is_temporary",
        ),
    ]
