# Generated by Django 5.2.5 on 2026-04-15 11:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_annotation", "0035_temporarypipeline_delete_anonymouspipeline_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnonymousUserQuota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("daily_jobs", models.IntegerField(default=0)),
                ("monthly_jobs", models.IntegerField(default=0)),
                ("daily_allele_queries", models.IntegerField(default=0)),
                ("monthly_allele_queries", models.IntegerField(default=0)),
                ("daily_variants", models.IntegerField(default=0)),
                ("monthly_variants", models.IntegerField(default=0)),
                ("daily_attributes", models.IntegerField(default=0)),
                ("monthly_attributes", models.IntegerField(default=0)),
                (
                    "last_daily_reset",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "last_monthly_reset",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("extra_jobs", models.IntegerField(default=0)),
                ("extra_allele_queries", models.IntegerField(default=0)),
                ("extra_variants", models.IntegerField(default=0)),
                ("extra_attributes", models.IntegerField(default=0)),
                ("ip", models.CharField(default="", max_length=256)),
            ],
            options={
                "db_table": "anonymous_user_quotas",
            },
        ),
        migrations.CreateModel(
            name="UserQuota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("daily_jobs", models.IntegerField(default=0)),
                ("monthly_jobs", models.IntegerField(default=0)),
                ("daily_allele_queries", models.IntegerField(default=0)),
                ("monthly_allele_queries", models.IntegerField(default=0)),
                ("daily_variants", models.IntegerField(default=0)),
                ("monthly_variants", models.IntegerField(default=0)),
                ("daily_attributes", models.IntegerField(default=0)),
                ("monthly_attributes", models.IntegerField(default=0)),
                (
                    "last_daily_reset",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "last_monthly_reset",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("extra_jobs", models.IntegerField(default=0)),
                ("extra_allele_queries", models.IntegerField(default=0)),
                ("extra_variants", models.IntegerField(default=0)),
                ("extra_attributes", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quota",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_quotas",
            },
        ),
    ]
