# Generated by Django 5.2.5 on 2026-04-20 10:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_annotation", "0035_temporarypipeline_delete_anonymouspipeline_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="allelequery",
            name="last_used",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="allelequery",
            name="note",
            field=models.CharField(default="", max_length=1024),
        ),
    ]
