# Generated by Django 5.2.5 on 2026-04-21 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web_annotation", "0036_allelequery_last_used_allelequery_note"),
        ("web_annotation", "0036_anonymoususerquota_userquota"),
    ]

    operations = []
